### PR TITLE
IAMv2 Updates

### PR DESCRIPTION
**Pull request by aedryan**
IAMv2 needs to handle jwks so we need to update our forked gem which has added support for that.

### CODE REVIEW

**Comment by britton** [comment]
I haven't tried validating an IAMv2 token, but I was able to test validating v1 tokens with this branch, and things seemed to work okay.

**Comment by britton** [comment]
I was able to verify that IAM v2 verification works, but wasn't able to get the JWK support to work (probably just not enough experimentation on my part).  I was able to verify an IAMv2 token by providing the public key manually to the JWT.decode method however.

**Review by britton — APPROVED** [review]

**Comment by britton** [comment]
@aedryan were you able to verify a v2 token using the jwk support in ruby-jwt?

**Comment by aedryan** [comment]
> @aedryan were you able to verify a v2 token using the jwk support in ruby-jwt?

I was, I got it working with our dev tokens here: https://github.com/semcat/skynet/pull/138/commits/7d0acce25efae1d1de5e627117c237649885597a
And got it working with an actual IAMv2 token with this fix: https://github.com/semcat/skynet/pull/138/commits/1054de3ea4c8e62d0bc7efb7af59dc0ac27f8a89

**Pull request merged**
